services:

  postgres:

    image: postgres:17

    container_name: devdocs-postgres

    restart: unless-stopped

    environment:

      POSTGRES_DB: devdocs

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

    ports:

      - "5432:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data
  

  grafana:
    image: grafana/grafana:latest

    container_name: devdocs-grafana

    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    depends_on:
      - postgres
      

volumes:

  postgres_data: